# Generated by Django 3.0.5 on 2020-04-12 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Specified'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, verbose_name="patient's full name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A+'), (2, 'B+'), (3, 'AB+'), (4, 'O+'), (5, 'A-'), (6, 'B-'), (7, 'AB-'), (8, 'O-')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_address', models.CharField(max_length=30)),
                ('super_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Region')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Region'),
        ),
    ]
