# Generated by Django 3.0.5 on 2020-04-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200412_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='super_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Region'),
        ),
    ]
