# Generated by Django 3.0.5 on 2020-04-12 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200412_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='case_number',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Specified'), (1, 'Fully Recovered'), (2, 'Under Treatment'), (3, 'Serious'), (4, 'Dead')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_infection',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Region'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Specified'), (1, 'A+'), (2, 'B+'), (3, 'AB+'), (4, 'O+'), (5, 'A-'), (6, 'B-'), (7, 'AB-'), (8, 'O-')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diseases',
            field=models.ManyToManyField(blank=True, to='backend.Disease'),
        ),
    ]
