# Generated by Django 3.0.5 on 2020-04-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200413_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='signs',
            field=models.ManyToManyField(blank=True, to='backend.Sign'),
        ),
    ]
